# Generated by Django 2.2.5 on 2019-09-25 02:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190923_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/Post_image/'),
            preserve_default=False,
        ),
    ]
